layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  facebook: abhishek.karve.37
  # hackerrank: your_username
  instagram: abhishekk2607
  # keybase: your_username
  linkedin: abhishek-karve-376028142
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  twitter: AbhishekKarve3
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  youtube: BeginnerScience

topics:
  - name: YouTube
    web_url: https://www.youtube.com/beginnerscience
    image_url: https://yt3.ggpht.com/ytc/AAUvwniEbKvCACHhvjCkIONPsUCex2GCZ8TYP3PC9HB2=s176-c-k-c0x00ffffff-no-rj

  - name: My Book
    web_url: https://www.amazon.in/Uprising-Battle-Principles-Abhishek-Karve-ebook/dp/B08FZLNLK3/ref=sr_1_2?dchild=1&keywords=An+Uprising&qid=1608032182&refinements=p_36%3A12124269031&rnid=12124266031&s=digital-text&sr=1-2
    image_url: https://m.media-amazon.com/images/I/41dzExOBfKL._SY346_.jpg

  - name: My Resume
    web_url: 
    image_url: https://freepngimg.com/thumb/resume/2-2-resume-transparent-thumb.png
